import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "../components/Home";
import About from "../components/About";
import Project from "../components/Projects";
import Contact from "../components/Contact";
import Loader from "../components/Loader";
const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <>
      <Head>
        <title>Eyuel Muler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/head.svg" />
      </Head>
      <Loader />
      <Hero />
      <About />
      <Project />
      <Contact />
    </>
  );
}
